# SAMPLE/DEMO Kubernetes NetworkPolicies for the FAST namespace.
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: fast
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-from-istio
  namespace: fast
spec:
  podSelector:
    matchLabels:
      exposure: corporate
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-fast-egress
  namespace: fast
spec:
  podSelector:
    matchLabels:
      tier: integration-runtime
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 10.50.10.0/24
        - ipBlock:
            cidr: 10.50.20.0/24
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 5432
    - to:
        - ipBlock:
            cidr: 10.70.10.0/24
        - ipBlock:
            cidr: 10.70.11.0/24
      ports:
        - protocol: TCP
          port: 443
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
