apiVersion: v1
kind: Namespace
metadata:
  name: fast
  labels:
    app.kubernetes.io/name: fast
    app.kubernetes.io/part-of: fast-platform
    # SAMPLE/DEMO marker for this repository.
    sample.proximus.be/profile: demo
